name: Update Latest Projects

on:
  schedule:
    - cron: "0 * * * *" # runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update latest repositories
    runs-on: ubuntu-latest
    steps:
      - name: Generate latest repos
        uses: Readme-Workflows/latest-repos@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: Abdulla6h77/Abdulla6h77
          MAX_REPOS: 5
